services:
  ospos-mysql-lib-unb-ca:
    image: mariadb:10.3
    command: mysqld --skip-name-resolve
    env_file:
      - ./env/mysql.env
    expose:
     - "3306"
    networks:
      - pos.lib.unb.ca

  pos.lib.unb.ca:
    build:
      context: .
    env_file:
      - ./env/ospos.env
    container_name: pos.lib.unb.ca
    expose:
      - "80"
    networks:
      - pos.lib.unb.ca
    ports:
      - "3103:80"

networks:
  pos.lib.unb.ca:
    name: pos.lib.unb.ca
